// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// ignore: unused_import
import 'dart:ffi';

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdlcBPvCetJHILtiXzdjqL41xiAJ7dxZo',
    appId: '1:220293392568:web:355932ec0a7a9c15546c4d',
    messagingSenderId: '220293392568',
    projectId: 'flutterloginregister-82be1',
    authDomain: 'flutterloginregister-82be1.firebaseapp.com',
    storageBucket: 'flutterloginregister-82be1.appspot.com',
    measurementId: 'G-NRYW45963K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoghCAQyGc2ut7xHXyUiuk5mfnXVe_swk',
    appId: '1:220293392568:android:b77abbe4fcc9a45c546c4d',
    messagingSenderId: '220293392568',
    projectId: 'flutterloginregister-82be1',
    storageBucket: 'flutterloginregister-82be1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtifRrdLBKrHirab35UmgACxqHr-yIFcg',
    appId: '1:220293392568:ios:c34fca62640b9bf1546c4d',
    messagingSenderId: '220293392568',
    projectId: 'flutterloginregister-82be1',
    storageBucket: 'flutterloginregister-82be1.appspot.com',
    iosBundleId: 'com.example.test12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtifRrdLBKrHirab35UmgACxqHr-yIFcg',
    appId: '1:220293392568:ios:c34fca62640b9bf1546c4d',
    messagingSenderId: '220293392568',
    projectId: 'flutterloginregister-82be1',
    storageBucket: 'flutterloginregister-82be1.appspot.com',
    iosBundleId: 'com.example.test12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdlcBPvCetJHILtiXzdjqL41xiAJ7dxZo',
    appId: '1:220293392568:web:f10f2a174a9dc7cf546c4d',
    messagingSenderId: '220293392568',
    projectId: 'flutterloginregister-82be1',
    authDomain: 'flutterloginregister-82be1.firebaseapp.com',
    storageBucket: 'flutterloginregister-82be1.appspot.com',
    measurementId: 'G-ETHTZVJ7BK',
  );
}